image: python:3.12

stages:
  - test

test-job:
  stage: test
  script:
    - pip install flask
    - pip install coverage
    - python -m coverage run -m unittest -v tests/appTest.py
    - python -m coverage report

test-job2:
  stage: test
  script:
    - echo "Executando o segundo job de teste"