image: python:3.12

stages:
  - test

test-job:
  stage: test
  script:
    - pip install flask
    - python -m unittest -v tests/appTest.py

test-job2:
  stage: test
  script:
    - echo "Executando o segundo job de teste"